name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: ~
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        dc: [dmd-2.097.2, dmd-2.099.1, dmd-2.100.2, ldc-1.27.1, ldc-1.29.0, ldc-1.30.0]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Run tests
      run: dub test
